export const CHANGE_GLOBAL = 'CHANGE_GLOBAL';
export const CHANGE_SIDEACTION = 'CHANGE_SIDEACTION';
export const CHANGE_REGION = 'CHANGE_REGION';
export const CHANGE_MENUTREE = 'CHANGE_MENUTREE';
export const CHANGE_PERMISSION = 'CHANGE_PERMISSION';
export const SET_NOTICE_DATA = 'SET_NOTICE_DATA';
// 所有修改state 在这里定义type(即方法名)
